### ISSUE TITLE
To Further Development

### ISSUE THREAD

**Issue by roniy68** [roniy68/portfolio#4]
**Attendtion : @Lancelot-SO  and @kazaneza**
***I want some inside ideas about this project to be further developed***

![issue](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQO2m8AU0AtL6O1aVOxWmfuQWMnSdA37esQbal3-jM&s)

**Comment by Lancelot-SO** [comment]
- [*****Attention : @roniy68******  ] 
************************************************
- [Please I want you to take not of your background image and align it properly. Also use float in styling your components ]

**Comment by roniy68** [comment]
# **Got it**
![got-it](https://media.tenor.com/RpxHe7IsxWIAAAAM/jim-carrey-ace-ventura.gif)

**Thanks ***@Lancelot-SO*** for your important insight**
* But I think I have used grid and flexbox to align items for the project. So, I will definitely keep in mind to use `float` s whenever possible

**Comment by roniy68** [comment]
@Lancelot-SO @Eugeneiyukhun 
**Could I ask for any other changes that I have to make in order to finish this project? [only the mobile version]**

![suggestion](https://media.giphy.com/media/l3vRdfbpN4kr1cn1m/giphy.gif)

I am going to suggest the change I want to make. You guys can give me suggestion about how can I add this to my project. 
- Adding Animation
- Adding Transition
- Adding media query
- etc

**Comment by annaeliana7** [comment]
### Great job on your project 🏆 

Your project is looking great!!! I have a minor suggestion regarding your five social buttons: to decrease the space between them. 
<img width="565" alt="Rony" src="https://user-images.githubusercontent.com/112557951/206127667-9736c2d7-90cf-4112-aa91-549e120b971b.png">

**Comment by roniy68** [comment]
# You are Right 💯 

***I think I should work more on the design***


<img src="https://media0.giphy.com/media/lqffDwBOYKwFHBfN9o/giphy.gif"/>

**Comment by Eugeneiyukhun** [comment]
**Good job so far!**
Can you kindly reduce the space in the social media link?

![lol](https://media.giphy.com/media/shZvUwpAALW4Dumm0Q/giphy.gif)

**Comment by roniy68** [comment]
**Great** @Eugeneiyukhun 
I think @annaeliana7 also mentioned about the spacing between the social media link. I will try to solve it as soon as possible. 
![](https://media.giphy.com/media/Guccz4Oq87bncsm1j4/giphy.gif)
***Thank you for the insight. I appreciate it so much***
